### ISSUE TITLE
XML Documentation

### ISSUE THREAD

**Issue by Ycreak** [bnagy/mqdq-parser#1]
Hi Bnagy! Do you have documentation for the meaning of your XML encoding? I understand the encoding of long and short syllables. From your code, I can see that SY means synalepha and CM means an accent (') on a syllable. But what does wb in wb="" stand for? And likewise its values CF, CM and DI (diaeresis I think). And sometimes instead of wb, there is mf. What does this mean?

I'm trying to build a classifier for scansion, using pedecerto to create a trainingset :D 

Cheers!

**Comment by bnagy** [comment]
Hi! The XML encoding comes from MQDQ/pedecerto. There's not much documentation over there either, but it's roughly this (copied from a pop-up in their site, no formatting, sorry). I've enabled the Discussions feature on the repo if you want to ask about it more...

I'd love to hear more about your project, by the way :) You might find something useful in my preprint https://arxiv.org/abs/1911.12478 if you haven't already seen it...



Attributes of line element
Attribute	Meaning	Values
name	verse line number	
metre	symbol of metrical pattern	H, P, A, Y, N, S, L, D, C, F, O, I, G, T, R, V (only H and P are scanned)
pattern	string of first 4 feet (D=dactyl, S=spondee); the fifth foot is indicated only if S	
features		spondaic, hypermeter
Attributes of the element word
Attribute	Meaning	Values
sy	syllables	A = arsis
T = thesis (spondee)
b / c = thesis (dactyl)
wb	word boundary	CM = male caesura
CF = female caesura
DI = diaeresis
mf	metrical features	SY = synalepha
HI = hiatus
HP = prosodic hiatus
DS = dropped final S
PE = prodelision
